; chr.s — generated by tools/make_chr.py  (do not edit by hand)
; 128x128 image encoded as NES 8x8 tiles in 2bpp CHR-ROM format
;
; Slot $00: blank tile
; Slots $01-$FF: image tiles 0-254 (row-major, TL to BR)
; Note: image tile 255 (bottom-right) also maps to slot $00.

.segment "CHARS"

; Tile $00: blank
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $01: image tile [0,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $02: image tile [0,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $03: image tile [0,2]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $04: image tile [0,3]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $05: image tile [0,4]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $06: image tile [0,5]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $07: image tile [0,6]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $08: image tile [0,7]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $09: image tile [0,8]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $0A: image tile [0,9]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $0B: image tile [0,10]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $0C: image tile [0,11]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $0D: image tile [0,12]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $0E: image tile [0,13]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $0F: image tile [0,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $10: image tile [0,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $11: image tile [1,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $12: image tile [1,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $13: image tile [1,2]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $14: image tile [1,3]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $15: image tile [1,4]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $16: image tile [1,5]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $17: image tile [1,6]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $18: image tile [1,7]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$01  ; plane 1

; Tile $19: image tile [1,8]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$7F,$D5  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$FF,$FF  ; plane 1

; Tile $1A: image tile [1,9]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$AA  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$FF,$FF  ; plane 1

; Tile $1B: image tile [1,10]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$AB  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$FF,$FF  ; plane 1

; Tile $1C: image tile [1,11]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$F6  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$FF,$FF  ; plane 1

; Tile $1D: image tile [1,12]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$4A,$B5  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$FF,$FF  ; plane 1

; Tile $1E: image tile [1,13]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$57,$AF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$F8,$F8  ; plane 1

; Tile $1F: image tile [1,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $20: image tile [1,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $21: image tile [2,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $22: image tile [2,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $23: image tile [2,2]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $24: image tile [2,3]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $25: image tile [2,4]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$DF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$20  ; plane 1

; Tile $26: image tile [2,5]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$01  ; plane 1

; Tile $27: image tile [2,6]
.byte $FF,$FF,$FF,$FF,$FE,$F8,$E0,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FD,$F7,$DF,$FF  ; plane 1

; Tile $28: image tile [2,7]
.byte $F8,$F0,$C1,$00,$09,$20,$05,$00  ; plane 0
.byte $FF,$EF,$BE,$FF,$F6,$DF,$FA,$FF  ; plane 1

; Tile $29: image tile [2,8]
.byte $00,$29,$40,$02,$48,$00,$00,$11  ; plane 0
.byte $FF,$D6,$BF,$FD,$B7,$FF,$FF,$EE  ; plane 1

; Tile $2A: image tile [2,9]
.byte $00,$2E,$05,$4B,$07,$22,$02,$29  ; plane 0
.byte $FF,$D1,$FA,$B4,$F8,$DD,$FD,$D6  ; plane 1

; Tile $2B: image tile [2,10]
.byte $00,$48,$02,$48,$00,$D1,$E0,$EC  ; plane 0
.byte $FF,$B7,$FD,$B7,$FF,$2E,$1F,$13  ; plane 1

; Tile $2C: image tile [2,11]
.byte $00,$00,$20,$00,$08,$40,$00,$14  ; plane 0
.byte $FD,$FE,$DE,$FF,$F7,$BF,$FF,$EB  ; plane 1

; Tile $2D: image tile [2,12]
.byte $00,$2A,$05,$14,$00,$10,$18,$6C  ; plane 0
.byte $FF,$C1,$B0,$41,$56,$47,$61,$12  ; plane 1

; Tile $2E: image tile [2,13]
.byte $03,$42,$2A,$05,$00,$00,$02,$00  ; plane 0
.byte $FF,$95,$80,$D0,$DF,$D7,$68,$2B  ; plane 1

; Tile $2F: image tile [2,14]
.byte $FF,$7F,$17,$56,$2A,$AA,$55,$2A  ; plane 0
.byte $FF,$83,$C8,$81,$80,$01,$80,$80  ; plane 1

; Tile $30: image tile [2,15]
.byte $FF,$FF,$FF,$7F,$5F,$1F,$4F,$2F  ; plane 0
.byte $FF,$FF,$FF,$BF,$BF,$EF,$8F,$97  ; plane 1

; Tile $31: image tile [3,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $32: image tile [3,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$F7,$FA  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$08,$05  ; plane 1

; Tile $33: image tile [3,2]
.byte $FF,$FF,$FF,$FB,$EF,$D7,$FF,$FF  ; plane 0
.byte $00,$00,$00,$04,$10,$28,$00,$00  ; plane 1

; Tile $34: image tile [3,3]
.byte $FF,$FF,$FD,$DF,$D7,$FD,$FF,$FD  ; plane 0
.byte $00,$00,$02,$20,$28,$02,$00,$02  ; plane 1

; Tile $35: image tile [3,4]
.byte $FF,$CF,$FF,$FF,$FE,$FB,$CB,$AF  ; plane 0
.byte $00,$30,$00,$00,$01,$04,$34,$50  ; plane 1

; Tile $36: image tile [3,5]
.byte $E7,$F5,$FF,$FF,$FF,$BF,$FF,$FE  ; plane 0
.byte $1F,$0F,$00,$00,$00,$40,$00,$01  ; plane 1

; Tile $37: image tile [3,6]
.byte $00,$50,$F0,$E0,$C0,$80,$80,$00  ; plane 0
.byte $FF,$BF,$EF,$DF,$BF,$7F,$7F,$FF  ; plane 1

; Tile $38: image tile [3,7]
.byte $00,$14,$00,$50,$00,$20,$00,$00  ; plane 0
.byte $FF,$EB,$FF,$AF,$FF,$DF,$FF,$FF  ; plane 1

; Tile $39: image tile [3,8]
.byte $00,$00,$08,$01,$00,$11,$00,$04  ; plane 0
.byte $FF,$FF,$F7,$FE,$FF,$EE,$FF,$FB  ; plane 1

; Tile $3A: image tile [3,9]
.byte $10,$44,$21,$48,$00,$42,$08,$00  ; plane 0
.byte $EF,$BB,$DE,$B7,$FF,$BD,$F7,$FF  ; plane 1

; Tile $3B: image tile [3,10]
.byte $6F,$1F,$40,$00,$10,$40,$02,$00  ; plane 0
.byte $90,$E0,$BF,$FF,$EF,$BF,$FD,$FF  ; plane 1

; Tile $3C: image tile [3,11]
.byte $B8,$A0,$00,$00,$00,$00,$10,$00  ; plane 0
.byte $47,$5F,$FF,$FF,$FF,$FF,$EF,$FF  ; plane 1

; Tile $3D: image tile [3,12]
.byte $78,$70,$01,$00,$40,$00,$00,$00  ; plane 0
.byte $05,$88,$04,$14,$0A,$2D,$55,$5A  ; plane 1

; Tile $3E: image tile [3,13]
.byte $00,$00,$06,$0B,$3E,$7D,$7F,$7E  ; plane 0
.byte $22,$95,$59,$50,$41,$00,$00,$80  ; plane 1

; Tile $3F: image tile [3,14]
.byte $00,$0A,$02,$15,$80,$A0,$70,$38  ; plane 0
.byte $FF,$70,$A8,$C0,$55,$4F,$A6,$15  ; plane 1

; Tile $40: image tile [3,15]
.byte $07,$27,$07,$47,$17,$07,$2F,$0F  ; plane 0
.byte $FF,$C7,$BB,$97,$47,$EF,$87,$D7  ; plane 1

; Tile $41: image tile [4,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $42: image tile [4,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $43: image tile [4,2]
.byte $FF,$FF,$FF,$F7,$FA,$DF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$08,$05,$20,$00,$00  ; plane 1

; Tile $44: image tile [4,3]
.byte $FF,$EA,$D3,$BF,$FF,$FF,$FD,$FF  ; plane 0
.byte $00,$15,$2C,$40,$00,$00,$02,$00  ; plane 1

; Tile $45: image tile [4,4]
.byte $FF,$AF,$FB,$ED,$F5,$EA,$F7,$DF  ; plane 0
.byte $00,$50,$04,$12,$0A,$15,$08,$20  ; plane 1

; Tile $46: image tile [4,5]
.byte $FD,$FF,$EF,$F7,$FF,$EF,$FF,$DF  ; plane 0
.byte $03,$03,$17,$0F,$0F,$1F,$1F,$3F  ; plane 1

; Tile $47: image tile [4,6]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 1

; Tile $48: image tile [4,7]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 1

; Tile $49: image tile [4,8]
.byte $00,$08,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$F7,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 1

; Tile $4A: image tile [4,9]
.byte $00,$00,$10,$00,$02,$00,$00,$00  ; plane 0
.byte $FF,$FF,$EF,$FF,$FD,$FF,$FF,$FF  ; plane 1

; Tile $4B: image tile [4,10]
.byte $00,$00,$00,$00,$10,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$EF,$FF,$FF,$FF  ; plane 1

; Tile $4C: image tile [4,11]
.byte $00,$00,$10,$30,$30,$78,$70,$F0  ; plane 0
.byte $FF,$FF,$EF,$CF,$DF,$97,$FF,$7F  ; plane 1

; Tile $4D: image tile [4,12]
.byte $00,$00,$04,$00,$08,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FB,$FF,$F7,$FF,$FF,$FF  ; plane 1

; Tile $4E: image tile [4,13]
.byte $28,$00,$00,$00,$00,$02,$00,$00  ; plane 0
.byte $D7,$87,$FF,$FF,$FF,$FD,$FF,$FF  ; plane 1

; Tile $4F: image tile [4,14]
.byte $FC,$FF,$EF,$FF,$FF,$FF,$F7,$F7  ; plane 0
.byte $E2,$E0,$F0,$F0,$F0,$F0,$F8,$F8  ; plane 1

; Tile $50: image tile [4,15]
.byte $0F,$BF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $10,$40,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $51: image tile [5,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $52: image tile [5,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $53: image tile [5,2]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $54: image tile [5,3]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $55: image tile [5,4]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$ED  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$12  ; plane 1

; Tile $56: image tile [5,5]
.byte $DF,$EB,$BF,$F7,$F7,$F7,$FF,$FF  ; plane 0
.byte $3B,$37,$47,$0F,$0F,$0F,$0F,$0F  ; plane 1

; Tile $57: image tile [5,6]
.byte $00,$00,$00,$00,$00,$00,$00,$01  ; plane 0
.byte $DF,$DF,$FF,$BF,$FF,$BF,$DF,$DF  ; plane 1

; Tile $58: image tile [5,7]
.byte $00,$00,$00,$00,$00,$00,$80,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF  ; plane 1

; Tile $59: image tile [5,8]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FF,$DF,$FF,$FF  ; plane 1

; Tile $5A: image tile [5,9]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 1

; Tile $5B: image tile [5,10]
.byte $00,$03,$07,$0F,$3F,$7F,$FF,$07  ; plane 0
.byte $FF,$FF,$FB,$FF,$CF,$9F,$0F,$0B  ; plane 1

; Tile $5C: image tile [5,11]
.byte $F0,$70,$F0,$F0,$F0,$F0,$F0,$F0  ; plane 0
.byte $7F,$BF,$FF,$FF,$FF,$FF,$F5,$EF  ; plane 1

; Tile $5D: image tile [5,12]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 1

; Tile $5E: image tile [5,13]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $F7,$FF,$E7,$FB,$EF,$E7,$D3,$AB  ; plane 1

; Tile $5F: image tile [5,14]
.byte $F7,$FF,$F7,$FF,$F7,$6F,$D7,$47  ; plane 0
.byte $F8,$F8,$F8,$F8,$F8,$68,$D8,$48  ; plane 1

; Tile $60: image tile [5,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $61: image tile [6,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $62: image tile [6,1]
.byte $FF,$FF,$FF,$EF,$EF,$E2,$20,$00  ; plane 0
.byte $00,$00,$00,$10,$11,$1E,$E0,$00  ; plane 1

; Tile $63: image tile [6,2]
.byte $F6,$E6,$CE,$7D,$EE,$EC,$FF,$E9  ; plane 0
.byte $09,$1B,$33,$93,$11,$13,$02,$14  ; plane 1

; Tile $64: image tile [6,3]
.byte $3F,$5F,$FF,$FF,$E4,$C0,$E0,$C8  ; plane 0
.byte $C0,$A0,$00,$00,$1E,$20,$20,$14  ; plane 1

; Tile $65: image tile [6,4]
.byte $FF,$FF,$FF,$F8,$02,$09,$24,$22  ; plane 0
.byte $FF,$FF,$FE,$F7,$ED,$36,$5B,$1D  ; plane 1

; Tile $66: image tile [6,5]
.byte $F0,$F2,$F6,$5F,$57,$5A,$57,$5A  ; plane 0
.byte $F0,$FE,$09,$A0,$A8,$A1,$A8,$A5  ; plane 1

; Tile $67: image tile [6,6]
.byte $DC,$EE,$FA,$77,$54,$03,$02,$43  ; plane 0
.byte $DF,$ED,$FD,$F4,$BF,$FF,$FD,$FC  ; plane 1

; Tile $68: image tile [6,7]
.byte $FF,$13,$A9,$AB,$FE,$27,$E7,$FF  ; plane 0
.byte $FF,$FF,$5E,$55,$03,$DC,$F8,$00  ; plane 1

; Tile $69: image tile [6,8]
.byte $BF,$F9,$FB,$7D,$FD,$FD,$FD,$FD  ; plane 0
.byte $BF,$FF,$87,$82,$02,$02,$02,$02  ; plane 1

; Tile $6A: image tile [6,9]
.byte $F7,$DF,$7F,$FF,$FF,$FF,$FF,$FE  ; plane 0
.byte $F8,$E0,$80,$00,$00,$00,$00,$01  ; plane 1

; Tile $6B: image tile [6,10]
.byte $E1,$C0,$86,$02,$00,$00,$38,$3C  ; plane 0
.byte $90,$BE,$FB,$FD,$FB,$FF,$C7,$C3  ; plane 1

; Tile $6C: image tile [6,11]
.byte $F0,$70,$30,$90,$C0,$40,$C0,$E0  ; plane 0
.byte $E0,$E4,$01,$04,$42,$E8,$12,$F0  ; plane 1

; Tile $6D: image tile [6,12]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $FF,$FF,$F6,$BD,$D4,$BA,$D1,$BE  ; plane 1

; Tile $6E: image tile [6,13]
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $AB,$49,$54,$4A,$52,$4A,$A9,$55  ; plane 1

; Tile $6F: image tile [6,14]
.byte $57,$A7,$2F,$9F,$4F,$5F,$5F,$5F  ; plane 0
.byte $58,$A8,$20,$90,$50,$40,$40,$60  ; plane 1

; Tile $70: image tile [6,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $71: image tile [7,0]
.byte $FC,$FC,$FC,$FC,$FE,$FE,$FF,$FF  ; plane 0
.byte $02,$00,$02,$02,$00,$01,$00,$00  ; plane 1

; Tile $72: image tile [7,1]
.byte $00,$00,$00,$00,$00,$00,$C0,$D5  ; plane 0
.byte $00,$00,$00,$00,$00,$88,$3F,$3F  ; plane 1

; Tile $73: image tile [7,2]
.byte $CD,$D8,$60,$00,$00,$00,$40,$13  ; plane 0
.byte $34,$31,$A0,$40,$00,$00,$FF,$EC  ; plane 1

; Tile $74: image tile [7,3]
.byte $9C,$5C,$1C,$38,$38,$78,$FB,$FB  ; plane 0
.byte $40,$E0,$20,$04,$44,$07,$04,$04  ; plane 1

; Tile $75: image tile [7,4]
.byte $24,$22,$29,$04,$01,$F0,$FE,$FF  ; plane 0
.byte $1B,$9D,$56,$7B,$7E,$2F,$FD,$FF  ; plane 1

; Tile $76: image tile [7,5]
.byte $56,$2B,$95,$4A,$25,$52,$03,$FF  ; plane 0
.byte $A9,$D4,$6A,$B5,$D8,$AD,$EC,$AF  ; plane 1

; Tile $77: image tile [7,6]
.byte $01,$55,$06,$06,$0F,$1D,$7F,$FD  ; plane 0
.byte $FE,$FA,$F9,$B9,$D0,$62,$80,$02  ; plane 1

; Tile $78: image tile [7,7]
.byte $FF,$FF,$FF,$7E,$7F,$BF,$9F,$CF  ; plane 0
.byte $00,$00,$01,$81,$80,$40,$60,$30  ; plane 1

; Tile $79: image tile [7,8]
.byte $FE,$FE,$BF,$A7,$DF,$47,$D3,$CB  ; plane 0
.byte $01,$01,$C0,$F8,$FC,$FC,$7C,$7C  ; plane 1

; Tile $7A: image tile [7,9]
.byte $FF,$FF,$FF,$9F,$DF,$FC,$F9,$FF  ; plane 0
.byte $00,$00,$80,$60,$30,$0F,$07,$00  ; plane 1

; Tile $7B: image tile [7,10]
.byte $39,$9B,$87,$FE,$FE,$F8,$00,$F8  ; plane 0
.byte $C6,$65,$79,$ED,$B0,$D0,$65,$82  ; plane 1

; Tile $7C: image tile [7,11]
.byte $E0,$C0,$00,$00,$00,$01,$00,$00  ; plane 0
.byte $C0,$82,$88,$15,$52,$28,$A7,$1F  ; plane 1

; Tile $7D: image tile [7,12]
.byte $0E,$1F,$3F,$3F,$5E,$BE,$7E,$FC  ; plane 0
.byte $F5,$4E,$D4,$46,$B9,$6F,$B5,$3F  ; plane 1

; Tile $7E: image tile [7,13]
.byte $00,$00,$00,$00,$04,$04,$0C,$1D  ; plane 0
.byte $55,$AA,$55,$B5,$A8,$AC,$AD,$B9  ; plane 1

; Tile $7F: image tile [7,14]
.byte $5F,$BF,$3F,$FF,$7F,$FF,$FF,$FF  ; plane 0
.byte $60,$80,$40,$80,$80,$00,$00,$00  ; plane 1

; Tile $80: image tile [7,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $81: image tile [8,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $82: image tile [8,1]
.byte $C5,$FF,$FF,$FF,$FF,$DF,$3F,$07  ; plane 0
.byte $3A,$00,$00,$00,$00,$20,$A0,$98  ; plane 1

; Tile $83: image tile [8,2]
.byte $EF,$9F,$FF,$BF,$FF,$FF,$FF,$FF  ; plane 0
.byte $10,$60,$00,$40,$00,$00,$00,$00  ; plane 1

; Tile $84: image tile [8,3]
.byte $F7,$FF,$EF,$FB,$FF,$FF,$FF,$FB  ; plane 0
.byte $08,$00,$10,$04,$00,$00,$00,$04  ; plane 1

; Tile $85: image tile [8,4]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$EF,$F5  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$10,$0A  ; plane 1

; Tile $86: image tile [8,5]
.byte $FF,$FF,$FF,$F7,$FF,$FF,$DC,$31  ; plane 0
.byte $00,$00,$00,$08,$00,$00,$3F,$CF  ; plane 1

; Tile $87: image tile [8,6]
.byte $FF,$FF,$FF,$F9,$BF,$FF,$FB,$3D  ; plane 0
.byte $00,$00,$00,$07,$40,$00,$04,$C2  ; plane 1

; Tile $88: image tile [8,7]
.byte $FF,$8F,$23,$51,$FF,$FA,$FC,$D9  ; plane 0
.byte $30,$48,$B4,$5E,$03,$06,$06,$29  ; plane 1

; Tile $89: image tile [8,8]
.byte $EF,$E7,$FF,$FF,$3F,$E7,$5D,$44  ; plane 0
.byte $38,$18,$00,$00,$C0,$F8,$5F,$5F  ; plane 1

; Tile $8A: image tile [8,9]
.byte $FF,$FF,$FF,$FF,$FF,$FD,$5B,$44  ; plane 0
.byte $00,$00,$00,$00,$00,$03,$FB,$F4  ; plane 1

; Tile $8B: image tile [8,10]
.byte $EF,$DE,$A6,$F7,$BD,$EA,$29,$82  ; plane 0
.byte $1F,$3F,$79,$0F,$7D,$EA,$2D,$A2  ; plane 1

; Tile $8C: image tile [8,11]
.byte $B4,$7F,$3F,$D3,$5F,$A2,$58,$81  ; plane 0
.byte $AF,$80,$C0,$DC,$5F,$A2,$5A,$A1  ; plane 1

; Tile $8D: image tile [8,12]
.byte $FB,$FE,$FB,$D4,$B3,$AF,$5D,$3F  ; plane 0
.byte $07,$06,$0B,$37,$F4,$A0,$62,$C0  ; plane 1

; Tile $8E: image tile [8,13]
.byte $9B,$3F,$7F,$DD,$F7,$FF,$DD,$F7  ; plane 0
.byte $A6,$44,$80,$22,$08,$00,$22,$08  ; plane 1

; Tile $8F: image tile [8,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $90: image tile [8,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $91: image tile [9,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $92: image tile [9,1]
.byte $07,$02,$00,$00,$00,$00,$00,$00  ; plane 0
.byte $1C,$87,$55,$20,$8A,$24,$52,$09  ; plane 1

; Tile $93: image tile [9,2]
.byte $F9,$55,$A1,$01,$01,$01,$01,$01  ; plane 0
.byte $06,$FC,$F0,$40,$14,$20,$4A,$24  ; plane 1

; Tile $94: image tile [9,3]
.byte $FF,$FF,$FF,$FF,$FC,$FC,$E0,$C0  ; plane 0
.byte $00,$00,$00,$00,$03,$07,$1F,$35  ; plane 1

; Tile $95: image tile [9,4]
.byte $E0,$C0,$C1,$09,$00,$2A,$00,$55  ; plane 0
.byte $1F,$3F,$3E,$F6,$FF,$D5,$FF,$AA  ; plane 1

; Tile $96: image tile [9,5]
.byte $70,$D5,$B8,$D6,$B5,$DF,$67,$2F  ; plane 0
.byte $8F,$2F,$47,$29,$4B,$27,$9F,$DF  ; plane 1

; Tile $97: image tile [9,6]
.byte $5F,$13,$BE,$7F,$EF,$DF,$EB,$BD  ; plane 0
.byte $E0,$FC,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 1

; Tile $98: image tile [9,7]
.byte $E6,$FF,$7D,$E3,$BE,$E7,$92,$C1  ; plane 0
.byte $1E,$01,$83,$FF,$BF,$E7,$93,$C1  ; plane 1

; Tile $99: image tile [9,8]
.byte $A4,$D5,$EA,$41,$9D,$17,$2A,$77  ; plane 0
.byte $AF,$DF,$EF,$F1,$FF,$FF,$FF,$FF  ; plane 1

; Tile $9A: image tile [9,9]
.byte $55,$16,$DE,$EE,$FA,$BF,$EF,$FE  ; plane 0
.byte $F5,$F6,$DE,$FF,$FE,$FC,$FC,$FF  ; plane 1

; Tile $9B: image tile [9,10]
.byte $55,$A2,$04,$20,$88,$28,$FC,$FD  ; plane 0
.byte $55,$AA,$45,$74,$E9,$DB,$05,$03  ; plane 1

; Tile $9C: image tile [9,11]
.byte $54,$C9,$41,$C3,$EF,$F3,$FF,$FF  ; plane 0
.byte $55,$8A,$AA,$24,$1C,$0C,$00,$00  ; plane 1

; Tile $9D: image tile [9,12]
.byte $FF,$FF,$FB,$FF,$F7,$EF,$FF,$DF  ; plane 0
.byte $00,$00,$04,$00,$08,$10,$00,$20  ; plane 1

; Tile $9E: image tile [9,13]
.byte $FF,$FF,$FB,$FF,$EF,$F7,$FF,$FF  ; plane 0
.byte $00,$00,$04,$00,$10,$08,$00,$00  ; plane 1

; Tile $9F: image tile [9,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $A0: image tile [9,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $A1: image tile [10,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $A2: image tile [10,1]
.byte $00,$00,$00,$00,$00,$00,$00,$60  ; plane 0
.byte $00,$55,$10,$A5,$88,$92,$C4,$82  ; plane 1

; Tile $A3: image tile [10,2]
.byte $01,$01,$00,$00,$00,$00,$00,$10  ; plane 0
.byte $EF,$BA,$D7,$AB,$AB,$AF,$5F,$EF  ; plane 1

; Tile $A4: image tile [10,3]
.byte $D1,$45,$22,$20,$0A,$21,$02,$02  ; plane 0
.byte $AE,$BA,$DD,$DF,$F5,$DE,$FD,$FD  ; plane 1

; Tile $A5: image tile [10,4]
.byte $FF,$FF,$FF,$FF,$7F,$7F,$3F,$9F  ; plane 0
.byte $00,$25,$08,$22,$81,$94,$C1,$74  ; plane 1

; Tile $A6: image tile [10,5]
.byte $A0,$C0,$E0,$E0,$F0,$F8,$FC,$FC  ; plane 0
.byte $41,$14,$05,$92,$45,$A0,$41,$50  ; plane 1

; Tile $A7: image tile [10,6]
.byte $55,$10,$50,$41,$20,$22,$04,$1E  ; plane 0
.byte $80,$41,$0E,$0C,$0C,$98,$3A,$81  ; plane 1

; Tile $A8: image tile [10,7]
.byte $00,$A8,$58,$F4,$68,$05,$00,$02  ; plane 0
.byte $A1,$04,$00,$01,$82,$70,$56,$A8  ; plane 1

; Tile $A9: image tile [10,8]
.byte $00,$00,$00,$00,$14,$42,$00,$42  ; plane 0
.byte $FF,$1F,$5F,$3F,$EB,$BD,$FF,$BD  ; plane 1

; Tile $AA: image tile [10,9]
.byte $00,$00,$04,$10,$01,$43,$07,$1F  ; plane 0
.byte $FF,$FF,$FB,$EF,$FE,$BF,$FE,$E7  ; plane 1

; Tile $AB: image tile [10,10]
.byte $3F,$3F,$7F,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $47,$00,$05,$16,$EB,$B5,$DF,$E8  ; plane 1

; Tile $AC: image tile [10,11]
.byte $FF,$FF,$FF,$FF,$FF,$EC,$EB,$B5  ; plane 0
.byte $FF,$6F,$9F,$8E,$EE,$B3,$80,$40  ; plane 1

; Tile $AD: image tile [10,12]
.byte $9F,$FF,$7F,$BF,$7F,$BF,$7F,$FF  ; plane 0
.byte $60,$40,$C0,$C0,$C0,$C0,$80,$80  ; plane 1

; Tile $AE: image tile [10,13]
.byte $FF,$FF,$FF,$FF,$DF,$DF,$FF,$DF  ; plane 0
.byte $00,$00,$00,$00,$20,$20,$00,$20  ; plane 1

; Tile $AF: image tile [10,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $B0: image tile [10,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $B1: image tile [11,0]
.byte $FF,$FE,$FE,$FF,$FF,$FF,$FE,$FF  ; plane 0
.byte $00,$01,$01,$00,$00,$00,$01,$00  ; plane 1

; Tile $B2: image tile [11,1]
.byte $72,$FD,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $8B,$03,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $B3: image tile [11,2]
.byte $A8,$50,$FC,$FC,$FC,$FE,$FE,$FE  ; plane 0
.byte $57,$AF,$07,$FF,$FF,$FD,$FC,$FD  ; plane 1

; Tile $B4: image tile [11,3]
.byte $02,$04,$02,$09,$0A,$08,$10,$08  ; plane 0
.byte $FD,$FB,$FD,$F6,$F5,$F6,$EF,$F6  ; plane 1

; Tile $B5: image tile [11,4]
.byte $2F,$BF,$77,$7B,$FD,$FA,$3C,$1C  ; plane 0
.byte $D2,$40,$8A,$84,$02,$05,$43,$E3  ; plane 1

; Tile $B6: image tile [11,5]
.byte $FE,$FF,$FF,$FF,$FF,$FF,$FF,$3F  ; plane 0
.byte $54,$50,$5D,$25,$55,$2A,$0A,$D3  ; plane 1

; Tile $B7: image tile [11,6]
.byte $1E,$0D,$90,$E8,$FE,$FF,$FF,$FF  ; plane 0
.byte $40,$B0,$62,$52,$81,$60,$AD,$52  ; plane 1

; Tile $B8: image tile [11,7]
.byte $04,$14,$28,$40,$2A,$FF,$FF,$FF  ; plane 0
.byte $B0,$C0,$81,$14,$81,$00,$40,$AA  ; plane 1

; Tile $B9: image tile [11,8]
.byte $00,$10,$00,$01,$7E,$AB,$FE,$F7  ; plane 0
.byte $7B,$63,$71,$14,$84,$2B,$5C,$05  ; plane 1

; Tile $BA: image tile [11,9]
.byte $1F,$3E,$15,$EF,$BD,$EE,$B7,$FA  ; plane 0
.byte $FF,$81,$41,$0A,$31,$4E,$35,$5A  ; plane 1

; Tile $BB: image tile [11,10]
.byte $FF,$BF,$FF,$FD,$FD,$F6,$EB,$AD  ; plane 0
.byte $C0,$40,$24,$02,$40,$08,$10,$40  ; plane 1

; Tile $BC: image tile [11,11]
.byte $CA,$B5,$5A,$A9,$6E,$AF,$6F,$AF  ; plane 0
.byte $35,$48,$80,$40,$80,$00,$84,$09  ; plane 1

; Tile $BD: image tile [11,12]
.byte $7F,$FF,$7F,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $80,$80,$80,$80,$00,$00,$00,$00  ; plane 1

; Tile $BE: image tile [11,13]
.byte $FF,$BF,$BF,$3F,$3F,$BF,$DF,$BF  ; plane 0
.byte $00,$40,$40,$C0,$C0,$C0,$60,$60  ; plane 1

; Tile $BF: image tile [11,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $C0: image tile [11,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $C1: image tile [12,0]
.byte $FF,$FE,$FF,$FE,$FF,$FE,$FF,$FE  ; plane 0
.byte $00,$01,$00,$01,$00,$01,$00,$01  ; plane 1

; Tile $C2: image tile [12,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $C3: image tile [12,2]
.byte $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FC  ; plane 0
.byte $FF,$FE,$FF,$FF,$FD,$FD,$FC,$F3  ; plane 1

; Tile $C4: image tile [12,3]
.byte $08,$14,$03,$23,$00,$00,$00,$28  ; plane 0
.byte $F6,$EB,$FC,$D4,$F3,$F7,$FE,$D6  ; plane 1

; Tile $C5: image tile [12,4]
.byte $0C,$02,$01,$80,$60,$70,$30,$00  ; plane 0
.byte $73,$DD,$BA,$6D,$92,$89,$CF,$FF  ; plane 1

; Tile $C6: image tile [12,5]
.byte $1F,$0F,$47,$01,$D0,$50,$5A,$55  ; plane 0
.byte $E5,$F0,$BA,$FE,$2F,$AF,$A5,$AA  ; plane 1

; Tile $C7: image tile [12,6]
.byte $FF,$FF,$FF,$FF,$7F,$0F,$00,$00  ; plane 0
.byte $AA,$55,$25,$90,$85,$F0,$FE,$FF  ; plane 1

; Tile $C8: image tile [12,7]
.byte $FF,$FF,$FF,$FF,$FF,$C2,$00,$00  ; plane 0
.byte $AA,$55,$AA,$21,$48,$3D,$FF,$FF  ; plane 1

; Tile $C9: image tile [12,8]
.byte $FF,$FF,$FF,$FF,$FE,$00,$00,$55  ; plane 0
.byte $40,$10,$A2,$00,$01,$FF,$FF,$AA  ; plane 1

; Tile $CA: image tile [12,9]
.byte $FF,$FE,$FD,$F2,$45,$15,$44,$55  ; plane 0
.byte $00,$05,$12,$0D,$BA,$EA,$BB,$AA  ; plane 1

; Tile $CB: image tile [12,10]
.byte $24,$92,$02,$24,$40,$05,$94,$07  ; plane 0
.byte $FF,$FF,$B7,$FF,$ED,$DF,$FF,$B0  ; plane 1

; Tile $CC: image tile [12,11]
.byte $4B,$4F,$5F,$3F,$BF,$7F,$FF,$FF  ; plane 0
.byte $F4,$F0,$E0,$C0,$C0,$80,$00,$00  ; plane 1

; Tile $CD: image tile [12,12]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $CE: image tile [12,13]
.byte $EF,$E7,$E3,$F7,$F9,$FD,$FE,$FF  ; plane 0
.byte $30,$18,$1C,$0C,$06,$03,$01,$00  ; plane 1

; Tile $CF: image tile [12,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$7F,$3F  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$80,$C0  ; plane 1

; Tile $D0: image tile [12,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $D1: image tile [13,0]
.byte $FE,$FF,$FE,$FE,$FE,$FF,$FF,$FF  ; plane 0
.byte $01,$00,$01,$01,$01,$00,$00,$00  ; plane 1

; Tile $D2: image tile [13,1]
.byte $FF,$FF,$FF,$FF,$FB,$6F,$3E,$3A  ; plane 0
.byte $00,$00,$00,$00,$04,$90,$C1,$C5  ; plane 1

; Tile $D3: image tile [13,2]
.byte $F8,$FC,$F0,$F0,$E0,$92,$AE,$2F  ; plane 0
.byte $FF,$F1,$FF,$E7,$CF,$ED,$51,$D0  ; plane 1

; Tile $D4: image tile [13,3]
.byte $1E,$3F,$2F,$3F,$9F,$5E,$4B,$80  ; plane 0
.byte $E1,$C0,$D1,$C4,$61,$A1,$B4,$7F  ; plane 1

; Tile $D5: image tile [13,4]
.byte $01,$02,$80,$C2,$41,$B4,$DA,$6D  ; plane 0
.byte $5E,$A5,$4F,$3D,$BE,$4B,$25,$92  ; plane 1

; Tile $D6: image tile [13,5]
.byte $56,$2D,$16,$4B,$25,$01,$A0,$00  ; plane 0
.byte $A9,$D2,$E9,$B4,$DA,$FE,$5F,$FF  ; plane 1

; Tile $D7: image tile [13,6]
.byte $80,$B5,$D0,$45,$CA,$4A,$8F,$0F  ; plane 0
.byte $7F,$4A,$2B,$B0,$30,$80,$66,$E3  ; plane 1

; Tile $D8: image tile [13,7]
.byte $24,$92,$45,$04,$20,$A2,$C0,$F8  ; plane 0
.byte $DB,$6D,$BA,$9B,$CE,$00,$18,$E2  ; plane 1

; Tile $D9: image tile [13,8]
.byte $42,$14,$A2,$08,$45,$10,$4A,$50  ; plane 0
.byte $BD,$EB,$5D,$F7,$BA,$EF,$35,$2F  ; plane 1

; Tile $DA: image tile [13,9]
.byte $4A,$24,$89,$07,$0F,$0F,$1F,$3F  ; plane 0
.byte $B5,$DB,$76,$F9,$F3,$FF,$EF,$DF  ; plane 1

; Tile $DB: image tile [13,10]
.byte $4F,$9F,$7F,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $F0,$E0,$80,$00,$00,$00,$00,$00  ; plane 1

; Tile $DC: image tile [13,11]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $DD: image tile [13,12]
.byte $FF,$FF,$FF,$FE,$FE,$FE,$FE,$FE  ; plane 0
.byte $00,$00,$00,$01,$00,$00,$00,$01  ; plane 1

; Tile $DE: image tile [13,13]
.byte $FF,$FF,$FF,$BF,$1F,$07,$07,$07  ; plane 0
.byte $00,$00,$00,$C0,$20,$08,$08,$40  ; plane 1

; Tile $DF: image tile [13,14]
.byte $9F,$CF,$F7,$FB,$FD,$FE,$FF,$FF  ; plane 0
.byte $60,$30,$08,$04,$02,$01,$00,$00  ; plane 1

; Tile $E0: image tile [13,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$BF,$DF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$40,$20  ; plane 1

; Tile $E1: image tile [14,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E2: image tile [14,1]
.byte $9D,$ED,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $63,$37,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E3: image tile [14,2]
.byte $00,$05,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $7F,$BA,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E4: image tile [14,3]
.byte $00,$00,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $E5,$D4,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E5: image tile [14,4]
.byte $00,$00,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $BF,$56,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E6: image tile [14,5]
.byte $00,$00,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $AA,$DA,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E7: image tile [14,6]
.byte $10,$00,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $5F,$8F,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E8: image tile [14,7]
.byte $FF,$33,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $03,$CF,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $E9: image tile [14,8]
.byte $80,$80,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $EA,$DA,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $EA: image tile [14,9]
.byte $3F,$3F,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $40,$C0,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $EB: image tile [14,10]
.byte $8F,$0F,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $40,$90,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $EC: image tile [14,11]
.byte $F8,$F0,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $07,$08,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $ED: image tile [14,12]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $EE: image tile [14,13]
.byte $87,$87,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $88,$08,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $EF: image tile [14,14]
.byte $FF,$7F,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$80,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F0: image tile [14,15]
.byte $EF,$FB,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $10,$04,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F1: image tile [15,0]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F2: image tile [15,1]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F3: image tile [15,2]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F4: image tile [15,3]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F5: image tile [15,4]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F6: image tile [15,5]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F7: image tile [15,6]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F8: image tile [15,7]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $F9: image tile [15,8]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $FA: image tile [15,9]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $FB: image tile [15,10]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $FC: image tile [15,11]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $FD: image tile [15,12]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $FE: image tile [15,13]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $FF: image tile [15,14]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

; Tile $00: image tile [15,15]
.byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; plane 0
.byte $00,$00,$00,$00,$00,$00,$00,$00  ; plane 1

