/*
 * main.c — NES slideshow: 10 images, A/Right=next, B/Left=prev
 *
 * Image layout: 256x160 px (32x20 tiles) at screen tile rows 4-23.
 *   Blank rows 0-3 (top) and 24-29 (bottom).
 *   Attribute rows 1-5 (PPU $23C8-$23EF) cover the image area.
 */

#define PPU_CTRL   (*(volatile unsigned char*)0x2000)
#define PPU_MASK   (*(volatile unsigned char*)0x2001)
#define PPU_STATUS (*(volatile unsigned char*)0x2002)
#define PPU_SCROLL (*(volatile unsigned char*)0x2005)
#define PPU_ADDR   (*(volatile unsigned char*)0x2006)
#define PPU_DATA   (*(volatile unsigned char*)0x2007)
#define JOY1       (*(volatile unsigned char*)0x4016)

/* LZE decoder interface: set ZP $1A-$1D then call lze_decode() */
#define LZE_SRC_LO (*(volatile unsigned char*)0x1A)
#define LZE_SRC_HI (*(volatile unsigned char*)0x1B)
#define LZE_DST_LO (*(volatile unsigned char*)0x1C)
#define LZE_DST_HI (*(volatile unsigned char*)0x1D)
void lze_decode(void);    /* asm/lzedec.s  */
void ppu_chr_copy(void);  /* asm/ppu_utils.s */

#include "../build/img_config.h"

/* Image data tables — generated by tools/make_chr.py → asm/img_data.s */
extern const unsigned char img_chr_lo[NUM_IMAGES];
extern const unsigned char img_chr_hi[NUM_IMAGES];
extern const unsigned char img_nt_lo[NUM_IMAGES];
extern const unsigned char img_nt_hi[NUM_IMAGES];
extern const unsigned char img_palettes[/* NUM_IMAGES * 16 */];
extern const unsigned char img_attrs[/* NUM_IMAGES * 40 */];

/*
 * PPU nametable row addresses for image area: screen tile rows 4-23, col 0.
 *   PPU address = $2000 + row * 32
 *   Row  4: $2080   Row  8: $2100   Row 16: $2200
 */
static const unsigned char NT_ROW_HI[20] = {
    0x20,0x20,0x20,0x20,
    0x21,0x21,0x21,0x21,0x21,0x21,0x21,0x21,
    0x22,0x22,0x22,0x22,0x22,0x22,0x22,0x22
};
static const unsigned char NT_ROW_LO[20] = {
    0x80,0xA0,0xC0,0xE0,
    0x00,0x20,0x40,0x60,0x80,0xA0,0xC0,0xE0,
    0x00,0x20,0x40,0x60,0x80,0xA0,0xC0,0xE0
};

#define BTN_A     0x80
#define BTN_B     0x40
#define BTN_RIGHT 0x01
#define BTN_LEFT  0x02

static unsigned char cur_image;
static unsigned char prev_pad;

/* -----------------------------------------------------------------------
 * read_pad — read NES controller 1 (returns A B Sel Start Up Down L R)
 * ----------------------------------------------------------------------- */
static unsigned char read_pad(void) {
    static unsigned char b;
    JOY1 = 1;
    JOY1 = 0;
    b  = 0;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1; b <<= 1;
    b |= JOY1 & 1;
    return b;
}

/* -----------------------------------------------------------------------
 * load_image — decompress + upload one image to PPU
 * ----------------------------------------------------------------------- */
static void load_image(unsigned char idx) {
    static unsigned char row, col, i;
    static unsigned char *nt_base;

    /* Disable rendering (forces blank; PPU is freely accessible) */
    PPU_CTRL = 0x00;
    PPU_MASK = 0x00;

    /* ---- Decompress CHR to WRAM $6000, then DMA to PPU CHR-RAM ---- */
    LZE_SRC_LO = img_chr_lo[idx];
    LZE_SRC_HI = img_chr_hi[idx];
    LZE_DST_LO = 0x00;
    LZE_DST_HI = 0x60;
    lze_decode();
    ppu_chr_copy();

    /* ---- Write 4 background palettes to PPU $3F00-$3F0F ---- */
    PPU_ADDR = 0x3F; PPU_ADDR = 0x00;
    for (i = 0; i < 16; i++) {
        PPU_DATA = img_palettes[(unsigned int)idx * 16 + i];
    }

    /* ---- Clear full nametable + attr table ($2000-$23FF, 1024 bytes) ---- */
    PPU_ADDR = 0x20; PPU_ADDR = 0x00;
    i = 0;
    do {
        PPU_DATA = 0; PPU_DATA = 0;
        PPU_DATA = 0; PPU_DATA = 0;
        i++;
    } while (i != 0);   /* 256 × 4 = 1024 bytes */

    /* ---- Decompress nametable to WRAM $7000, then write 20 rows ---- */
    LZE_SRC_LO = img_nt_lo[idx];
    LZE_SRC_HI = img_nt_hi[idx];
    LZE_DST_LO = 0x00;
    LZE_DST_HI = 0x70;
    lze_decode();
    nt_base = (unsigned char *)0x7000;
    for (row = 0; row < 20; row++) {
        PPU_ADDR = NT_ROW_HI[row];
        PPU_ADDR = NT_ROW_LO[row];
        for (col = 0; col < 32; col++) {
            PPU_DATA = nt_base[col];
        }
        nt_base += 32;
    }

    /* ---- Write attribute bytes for image area: 5×8=40 bytes at $23C8 ---- */
    PPU_ADDR = 0x23; PPU_ADDR = 0xC8;
    for (i = 0; i < 40; i++) {
        PPU_DATA = img_attrs[(unsigned int)idx * 40 + i];
    }

    /* ---- Re-enable rendering ---- */
    PPU_SCROLL = 0; PPU_SCROLL = 0;
    PPU_CTRL = 0x80;  /* NMI on, BG pattern table $0000 */
    PPU_MASK = 0x0A;  /* show background */
}

/* -----------------------------------------------------------------------
 * main
 * ----------------------------------------------------------------------- */
void main(void) {
    static unsigned char curr_pad, pressed;

    PPU_CTRL = 0x00;
    PPU_MASK = 0x00;

    /* Wait for PPU ready (2 vblanks) */
    while (!(PPU_STATUS & 0x80)) {}
    while (!(PPU_STATUS & 0x80)) {}

    cur_image = 0;
    prev_pad  = 0;
    load_image(0);

    while (1) {
        /* Throttle: wait for vblank before sampling input */
        while (!(PPU_STATUS & 0x80)) {}

        curr_pad = read_pad();
        pressed  = curr_pad & ~prev_pad;
        prev_pad = curr_pad;

        if (pressed & (BTN_A | BTN_RIGHT)) {
            if (cur_image + 1 < NUM_IMAGES)
                cur_image++;
            else
                cur_image = 0;
            load_image(cur_image);
        } else if (pressed & (BTN_B | BTN_LEFT)) {
            if (cur_image > 0)
                cur_image--;
            else
                cur_image = NUM_IMAGES - 1;
            load_image(cur_image);
        }
    }
}
